### ISSUE TITLE
Update to new API version

### ISSUE THREAD

**Issue by Eluinhost** [Eluinhost/TSVerificationChecker#3]

**Comment by ghost** [comment]
Relevant error using spigot 1.10 and auth.uhc.gg for testing (Fixed with SpecialSource)

```
[02:12:32 INFO]: TiTo_418 issued server command: /tsverificationchecker:tsverify true *
[02:12:33 WARN]: java.text.ParseException: Invalid JSON file
[02:12:33 WARN]:        at com.publicuhc.tsverificationchecker.DefaultVerificationChecker.getVerificationResponseForUUIDs(DefaultVerificationChecker.java:47)
[02:12:33 WARN]:        at com.publicuhc.tsverificationchecker.commands.AsyncVerificationCheck.run(AsyncVerificationCheck.java:39)
[02:12:33 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
[02:12:33 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[02:12:33 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[02:12:33 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[02:12:33 WARN]:        at java.lang.Thread.run(Unknown Source)
```

**Comment by Eluinhost** [comment]
I've pushed a quick WIP version to https://github.com/Eluinhost/TSVerificationChecker/tree/kotlinise I'm pretty sure there will be issues with https though as Java doesn't recognise StartCOM as a proper CA yet. People can add the certs to their keystore but that's a bit much to ask. I'm pretty sure I can just bundle the certs in the plugin resources and instruct Fuel to use a custom keystore if the base path contains `uhc.gg` though, something to look into

**Comment by ghost** [comment]
Error using default config: http://pastebin.com/g1p4D7JZ
Spigot 1.10

**Comment by Eluinhost** [comment]
Yup that's the SSL error I was talking about, I'll take a look at seeing if it's easy solvable tomorrow if I get time and maybe actually run it instead of just compiling :P
